[features]
seeds = false
[programs.localnet]
solana_twitter = "5378ybCoRKNx2VdrEu7k2BnNuK1q219CybXNwXM4zaFo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/patoverde/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my_script = "echo 'hello world!'"
